language: node_js

node_js:
    - stable

script:
    - npm run lint
    - npm run test

after_script:
    - npx codecov

cache:
    directories:
        - node_modules

matrix:
    fast_finish: true
